"""Type stubs for the compiled ``citadeldb._core`` extension."""

from typing import Any

import numpy

__version__: str

# --- exceptions -------------------------------------------------------------

class CitadelError(Exception): ...
class EncryptionError(CitadelError): ...
class IntegrityError(CitadelError): ...
class OperationalError(CitadelError): ...
class ProgrammingError(CitadelError): ...
class DataError(CitadelError): ...
class NotSupportedError(CitadelError): ...
class LlmError(CitadelError): ...
class AgentError(CitadelError): ...

# --- console-script entry points --------------------------------------------

def cli_main(argv: list[str]) -> int: ...
def mcp_main(argv: list[str]) -> int: ...

# --- encrypted SQL ----------------------------------------------------------

def connect(
    path: str | None = ...,
    *,
    key: str,
    create: bool | None = ...,
    region_keys: bool = ...,
    options: DatabaseOptions | None = ...,
) -> Database: ...

class Database:
    def execute(self, sql: str, params: list[Any] | None = ...) -> int | QueryResult | None: ...
    def query(self, sql: str, params: list[Any] | None = ...) -> QueryResult: ...
    def execute_script(self, sql: str) -> list[Any]: ...
    def tables(self) -> list[str]: ...
    def in_transaction(self) -> bool: ...
    def memory(self) -> Memory: ...
    def stats(self) -> dict[str, Any]: ...
    def integrity_check(self) -> dict[str, Any]: ...
    def backup(self, dest: str) -> None: ...
    def compact(self, dest: str) -> None: ...
    def change_passphrase(self, old: str, new: str) -> None: ...
    def persist_ann_index(self, table: str, column: str) -> dict[str, Any]: ...
    def ann_cache_status(self, table: str, column: str) -> dict[str, Any] | None: ...
    def export_key_backup(self, db_pass: str, backup_pass: str, dest: str) -> None: ...
    @staticmethod
    def restore_key_from_backup(
        backup: str, backup_pass: str, new_db_pass: str, db_path: str
    ) -> None: ...
    def verify_audit_log(self) -> dict[str, Any]: ...
    def audit_log_path(self) -> str | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Database: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...

class QueryResult:
    columns: list[str]
    @property
    def rows(self) -> list[tuple[Any, ...]]: ...
    def to_dicts(self) -> list[dict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class DatabaseOptions:
    def __init__(
        self,
        *,
        secure_delete: bool = ...,
        cache_size: int | None = ...,
        sync_mode: str | None = ...,
        cipher: str | None = ...,
        kdf: str | None = ...,
        pbkdf2_iterations: int | None = ...,
        argon2_profile: str | None = ...,
    ) -> None: ...

# --- vector search ----------------------------------------------------------

class VectorIndex:
    def __init__(
        self,
        vectors: numpy.ndarray,
        ids: numpy.ndarray,
        metric: str = ...,
        *,
        attrs: numpy.ndarray | None = ...,
    ) -> None: ...
    def search(
        self,
        query: numpy.ndarray,
        k: int = ...,
        *,
        ef: int | None = ...,
        filter: Filter | None = ...,
    ) -> tuple[numpy.ndarray, numpy.ndarray]: ...
    @property
    def dim(self) -> int: ...
    @property
    def metric(self) -> str: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Filter:
    def __init__(self, constraints: list[tuple[int, list[int]]] | None = ...) -> None: ...
    @staticmethod
    def eq(attr: int, val: int) -> Filter: ...
    def strength(self) -> int: ...

def vector_l2_squared(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def vector_inner_product(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def vector_cosine(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def vector_distance(a: numpy.ndarray, b: numpy.ndarray, metric: str = ...) -> float: ...
def vector_normalize(v: numpy.ndarray) -> numpy.ndarray: ...

# --- memory engine ----------------------------------------------------------

class MockEmbedder:
    def __init__(self, dim: int, metric: str = ...) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def metric(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def embed_queries(self, texts: list[str]) -> list[list[float]]: ...

class CandleEmbedder:
    """Only present in builds with the ``candle-embed`` feature."""

    def __init__(self, model_dir: str, preset: str = ...) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def metric(self) -> str: ...
    @property
    def model_id(self) -> str: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def embed_queries(self, texts: list[str]) -> list[list[float]]: ...

class MockReranker:
    def __init__(self) -> None: ...

class CrossEncoder:
    """Only present in builds with the ``candle-embed`` feature."""

    def __init__(self, model_dir: str) -> None: ...
    @property
    def model_id(self) -> str: ...

class AtomHit:
    id: int
    kind: str
    text: str
    distance: float
    score: float
    created_at: int
    immutable: bool
    @property
    def payload(self) -> Any: ...
    def __repr__(self) -> str: ...

class EvictionPolicy:
    @staticmethod
    def stale(older_than_micros: int) -> EvictionPolicy: ...
    @staticmethod
    def lru(keep_fraction: float) -> EvictionPolicy: ...
    @staticmethod
    def low_score(score_threshold: float, confidence_threshold: float) -> EvictionPolicy: ...
    @staticmethod
    def purge_region() -> EvictionPolicy: ...
    @staticmethod
    def predicate_match(predicate: Any) -> EvictionPolicy: ...

class SlotErasure:
    @property
    def slot(self) -> int: ...
    @property
    def atom_id(self) -> int: ...
    @property
    def old_gen(self) -> int: ...
    @property
    def new_gen(self) -> int: ...
    def __repr__(self) -> str: ...

class ErasureReceipt:
    @property
    def cryptographic_erasure(self) -> bool: ...
    @property
    def rows_deleted(self) -> int: ...
    @property
    def erased_count(self) -> int: ...
    @property
    def immutable_skipped(self) -> list[int]: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def readback_confirmed(self) -> bool: ...
    @property
    def scope_caveat(self) -> str: ...
    @property
    def slots_erased(self) -> list[SlotErasure]: ...
    @property
    def wrapped_key_size(self) -> int: ...
    @property
    def fsync(self) -> bool: ...
    def __repr__(self) -> str: ...

class AtomAttestation:
    @property
    def atom_id(self) -> int: ...
    @property
    def verdict(self) -> str: ...
    @property
    def aad_bound(self) -> bool: ...
    @property
    def key_slot(self) -> int | None: ...
    @property
    def key_gen(self) -> int | None: ...
    def __repr__(self) -> str: ...

class RecallOptions:
    def __init__(
        self,
        *,
        payload_filter: Any | None = ...,
        weights: tuple[float, float, float, float] | None = ...,
        as_of_micros: int | None = ...,
        graph_expand: tuple[int, list[str]] | None = ...,
    ) -> None: ...

class Memory:
    def create_region(self, name: str, embedder: Any) -> int: ...
    def create_encrypted_region(self, name: str, embedder: Any) -> int: ...
    def drop_region(self, name: str) -> None: ...
    def remember(self, region: str, atom: dict[str, Any]) -> int: ...
    def remember_batch(self, region: str, atoms: list[dict[str, Any]]) -> list[int]: ...
    def recall(
        self,
        region: str,
        *,
        text: str | None = ...,
        embedding: list[float] | None = ...,
        k: int = ...,
        kinds: list[str] | None = ...,
        options: RecallOptions | None = ...,
    ) -> list[AtomHit]: ...
    def fetch(
        self,
        region: str,
        kind: str,
        *,
        payload_filter: Any | None = ...,
        limit: int = ...,
    ) -> list[AtomHit]: ...
    def fetch_one(self, region: str, atom_id: int) -> AtomHit | None: ...
    def count(self, region: str, kind: str) -> int: ...
    def link(self, src: int, dst: int, kind: str, weight: float = ...) -> None: ...
    def evict(self, region: str, policy: EvictionPolicy) -> int: ...
    def forget(self, region: str, ids: list[int], force: bool = ...) -> ErasureReceipt: ...
    def verify(self, region: str, ids: list[int]) -> list[AtomAttestation]: ...
    def update_atom_payload(self, region: str, atom_id: int, payload: Any) -> None: ...
    def fetch_last(self, region: str, kind: str) -> AtomHit | None: ...
    def fetch_edges(
        self,
        *,
        src: int | None = ...,
        dst: int | None = ...,
        kind: str | None = ...,
    ) -> list[dict[str, Any]]: ...
    def evolve(self, region: str, atom_id: int, neighbors: int, max_distance: float) -> dict[str, Any]: ...
    def summarize(self, region: str, since_micros: int) -> dict[str, Any]: ...
    def set_reranker(self, reranker: Any, *, strategy: str = ..., rrf_k: float = ...) -> None: ...
    def clear_reranker(self) -> None: ...
    def persist_ann_index(self, region: str) -> dict[str, Any]: ...
    def ann_cache_status(self, region: str) -> dict[str, Any] | None: ...

# --- LLM client -------------------------------------------------------------

class LLMClient:
    @staticmethod
    def provider(provider: str, model: str) -> LLMClient: ...
    @staticmethod
    def from_env(prefix: str, default_provider: str, default_model: str) -> LLMClient: ...
    @staticmethod
    def mock() -> LLMClient: ...
    @staticmethod
    def replay(graph: BeliefGraph) -> LLMClient: ...
    @property
    def model_id(self) -> str: ...
    @property
    def replay_misses(self) -> int | None: ...
    def count_tokens(self, messages: list[dict[str, Any]]) -> int: ...
    def complete(self, request: dict[str, Any]) -> dict[str, Any]: ...

# --- belief-graph data types ------------------------------------------------

class Goal:
    def __init__(
        self,
        prompt: str,
        *,
        acceptance_criteria: list[str] | None = ...,
        constraints: list[str] | None = ...,
        target: str | None = ...,
    ) -> None: ...
    @property
    def prompt(self) -> str: ...
    @property
    def acceptance_criteria(self) -> list[str]: ...
    @property
    def constraints(self) -> list[str]: ...
    @property
    def target(self) -> str | None: ...
    def __repr__(self) -> str: ...

class Task:
    def __init__(
        self,
        description: str,
        *,
        status: str = ...,
        attempts: int = ...,
        last_error: str | None = ...,
    ) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def attempts(self) -> int: ...
    @property
    def last_error(self) -> str | None: ...
    def __repr__(self) -> str: ...

class Hypothesis:
    def __init__(self, summary: str, confidence: float = ...) -> None: ...
    @property
    def summary(self) -> str: ...
    @property
    def confidence(self) -> float: ...

class Evidence:
    def __init__(self, source: str, content: str) -> None: ...
    @property
    def source(self) -> str: ...
    @property
    def content(self) -> str: ...

class Reflection:
    def __init__(self, insight: str, confidence: float = ...) -> None: ...
    @property
    def insight(self) -> str: ...
    @property
    def confidence(self) -> float: ...

class SelfModel:
    def __init__(self, identity: str, *, goal_ref: int | None = ...) -> None: ...
    @property
    def identity(self) -> str: ...
    @property
    def goal_ref(self) -> int | None: ...
    def __repr__(self) -> str: ...

class CoInstantiationCheck:
    def __init__(
        self,
        action_id: str,
        goal_ref: int,
        self_model_ref: int,
        has_provenance: bool,
        constraints_satisfied: bool,
        drift_count: int,
        drift_bound: int,
    ) -> None: ...
    @property
    def version(self) -> int: ...
    @property
    def action_id(self) -> str: ...
    @property
    def goal_ref(self) -> int: ...
    @property
    def self_model_ref(self) -> int: ...
    @property
    def has_provenance(self) -> bool: ...
    @property
    def constraints_satisfied(self) -> bool: ...
    @property
    def verdict(self) -> str: ...
    @property
    def drift_count(self) -> int: ...
    @property
    def drift_bound(self) -> int: ...
    @property
    def timestamp_micros(self) -> int: ...
    @property
    def prev_hash(self) -> str: ...
    @property
    def this_hash(self) -> str: ...
    def __repr__(self) -> str: ...

class ChainReport:
    @property
    def valid(self) -> bool: ...
    @property
    def total_checks(self) -> int: ...
    @property
    def breaches(self) -> list[tuple[int, str]]: ...
    def __repr__(self) -> str: ...

class VerifiedExport:
    @property
    def atom(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def artifact(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def checker_id(self) -> str: ...
    @property
    def checker_version(self) -> str: ...
    @property
    def checked_at_micros(self) -> int: ...

class TraceEvictionPolicy:
    @staticmethod
    def keep_last_n(n: int) -> TraceEvictionPolicy: ...
    @staticmethod
    def by_age(older_than_micros: int) -> TraceEvictionPolicy: ...
    @staticmethod
    def by_total_cost(max_cost_usd: float) -> TraceEvictionPolicy: ...

class BeliefGraph:
    def __init__(self, memory: Memory, region: str) -> None: ...
    def add_goal(self, goal: Goal) -> int: ...
    def add_task(self, task: Task, deps: list[int], goal_id: int) -> int: ...
    def add_hypothesis(self, hypothesis: Hypothesis, refines_goal: int) -> int: ...
    def add_evidence(self, evidence: Evidence, supports: int) -> int: ...
    def add_reflection(self, reflection: Reflection, about: int) -> int: ...
    def add_candidate(self, artifact: str, score: float) -> int: ...
    def add_verified_artifact(
        self,
        candidate_atom: int,
        kind: str,
        checker_id: str,
        checker_version: str,
        score: float,
    ) -> int: ...
    def set_goal_status(self, goal_id: int, status: str) -> None: ...
    def update_task(self, id: int, task: Task) -> None: ...
    def set_task_status(self, id: int, status: str) -> None: ...
    def record_task_failure(self, id: int, error: str) -> None: ...
    def set_self_model(self, self_model: SelfModel) -> int: ...
    def supersede_self_model(self, self_model: SelfModel) -> int: ...
    def record_check(self, check: CoInstantiationCheck, action_atom: int) -> int: ...
    def record_llm_call(
        self,
        request_hash: str,
        model_id: str,
        response: dict[str, Any],
        cost_usd: float | None = ...,
        prompt: Any | None = ...,
    ) -> int: ...
    def get_goal(self, id: int) -> Goal | None: ...
    def get_goal_status(self, goal_id: int) -> str | None: ...
    def get_task(self, id: int) -> Task | None: ...
    def tasks(self) -> list[tuple[int, Task]]: ...
    def next_unblocked_tasks(self) -> list[tuple[int, Task]]: ...
    def current_self_model_id(self) -> int | None: ...
    def current_self_model(self) -> SelfModel | None: ...
    def top_scored(self, kinds: list[str], k: int) -> list[tuple[int, str, float]]: ...
    def export_verified_artifact(self, atom: int) -> VerifiedExport | None: ...
    def evidence_for_goal(self, goal_id: int) -> list[tuple[str, str]]: ...
    def recall_relevant(self, query: str, k: int) -> list[AtomHit]: ...
    def load_llm_traces(self) -> list[tuple[str, Any]]: ...
    def llm_model_id(self) -> str | None: ...
    def has_provenance(self, action_atom: int, goal_ref: int) -> bool: ...
    def verify_self_model_chain(self) -> None: ...
    def verify_chain(self) -> ChainReport: ...
    def export_audit_trail(self) -> list[CoInstantiationCheck]: ...
    def evict_guarded(self, policy: EvictionPolicy, force: bool = ...) -> int: ...
    def evict_traces(self, policy: TraceEvictionPolicy) -> int: ...

# --- agent runtime ----------------------------------------------------------

class AgentBudget:
    def __init__(
        self,
        *,
        max_steps: int | None = ...,
        max_tokens: int | None = ...,
        max_wall_secs: int | None = ...,
        max_cost_usd: float | None = ...,
        max_proposals: int | None = ...,
        max_checker_calls: int | None = ...,
    ) -> None: ...
    @property
    def max_steps(self) -> int: ...
    @property
    def max_tokens(self) -> int: ...
    @property
    def max_wall_secs(self) -> int: ...
    @property
    def max_cost_usd(self) -> float | None: ...
    @property
    def max_proposals(self) -> int: ...
    @property
    def max_checker_calls(self) -> int: ...

class LlmProposer:
    def __init__(
        self,
        *,
        temperature: float = ...,
        max_tokens: int | None = ...,
        artifact_schema: Any | None = ...,
        plain_json: bool = ...,
    ) -> None: ...

class Completer:
    def complete(self, request: dict[str, Any]) -> dict[str, Any]: ...

class PromptLibrary:
    def __init__(self) -> None: ...
    def set(self, id: str, version: int, text: str) -> None: ...
    def resolve(self, id: str) -> str: ...
    @staticmethod
    def from_region(memory: Memory, region: str) -> PromptLibrary: ...

class AgentConfig:
    def __init__(self) -> None: ...
    drift_bound: int
    max_replans: int
    max_tool_attempts: int
    max_react_steps: int
    max_repairs: int
    recall_context_k: int
    temperature: float
    def set_retry(self, base_ms: int, max_ms: int) -> None: ...
    def set_recall_context_weights(
        self,
        semantic: float,
        keyword: float,
        recency: float,
        importance: float,
    ) -> None: ...
    def set_recall_context_graph_expand(self, depth: int, edge_kinds: list[str]) -> None: ...
    def clear_recall_context_graph_expand(self) -> None: ...
    def set_verifier(self, verifier: Any) -> None: ...
    def set_proposal_operator(self, proposer: Any) -> None: ...
    def set_prompt_library(self, library: PromptLibrary) -> None: ...

class DiscoveryGoal:
    def __init__(
        self,
        goal: Goal,
        *,
        kind: str = ...,
        baseline_score: float = ...,
        archive_width: int = ...,
        max_idle_rounds: int = ...,
        max_mints: int = ...,
    ) -> None: ...
    @property
    def goal(self) -> Goal: ...
    @property
    def kind(self) -> str: ...
    @property
    def baseline_score(self) -> float: ...
    @property
    def archive_width(self) -> int: ...
    @property
    def max_idle_rounds(self) -> int: ...
    @property
    def max_mints(self) -> int: ...

class AgentReport:
    @property
    def goal_id(self) -> int | None: ...
    @property
    def final_answer(self) -> str | None: ...
    @property
    def tasks_done(self) -> int: ...
    @property
    def terminated_by(self) -> str: ...
    @property
    def budget_exceeded(self) -> str | None: ...
    @property
    def chain_valid(self) -> bool: ...
    def __repr__(self) -> str: ...

class DiscoveryReport:
    @property
    def best_score(self) -> float: ...
    @property
    def best_artifact(self) -> Any | None: ...
    @property
    def verified(self) -> int | None: ...
    @property
    def minted(self) -> list[int]: ...
    @property
    def proposals(self) -> int: ...
    @property
    def checker_calls(self) -> int: ...
    @property
    def best_valid_score(self) -> float: ...
    @property
    def valid_candidates(self) -> int: ...
    @property
    def sample_reject_reason(self) -> str | None: ...
    @property
    def barren_rounds(self) -> int: ...
    @property
    def cross_check_failures(self) -> int: ...
    @property
    def terminated_by(self) -> str: ...
    @property
    def budget_exceeded(self) -> str | None: ...
    @property
    def chain_valid(self) -> bool: ...

class ToolRegistry:
    def __init__(self) -> None: ...
    def register(self, tool: Any) -> None: ...
    def add_mem_recall(self, memory: Memory, region: str) -> None: ...
    def add_mem_remember(self, memory: Memory, region: str) -> None: ...
    def add_file_read(self, allowed: list[str]) -> None: ...
    def add_file_write(self, allowed: list[str]) -> None: ...
    def add_list_dir(self, allowed: list[str]) -> None: ...
    def add_run_command(self, allowed: list[str], workdir: str, timeout_ms: int) -> None: ...
    def names(self) -> list[str]: ...
    def contains(self, name: str) -> bool: ...
    def specs(self) -> list[dict[str, Any]]: ...
    def permissions(self, name: str) -> dict[str, Any] | None: ...

class Agent:
    def __init__(
        self,
        memory: Memory,
        region: str,
        llm: Any,
        *,
        tools: ToolRegistry | None = ...,
        budget: AgentBudget | None = ...,
        config: AgentConfig | None = ...,
    ) -> None: ...
    def run(self, prompt: str) -> AgentReport: ...
    def run_discovery(self, goal: DiscoveryGoal) -> DiscoveryReport: ...
    def graph(self) -> BeliefGraph: ...
