language = "C"
include_guard = "CITADEL_H"
tab_width = 4
documentation_style = "doxy"
style = "both"
cpp_compat = true
after_includes = "\n#ifndef CITADEL_API\n#define CITADEL_API\n#endif"

[defines]
"feature = io-uring" = "CITADEL_IO_URING"

[export]
include = [
    "citadel_error_t",
    "CitadelConfig",
]

[export.rename]
"CitadelError" = "citadel_error_t"

[fn]
prefix = "CITADEL_API"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[parse]
parse_deps = false
